version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    environment:
      - "JEKYLL_GITHUB_TOKEN:${JEKYLL_GITHUB_TOKEN}"
    ports:
      - target: 4000
        published: '${SERVE_PORT}'
        protocol: tcp
        mode: host
    volumes:
      - ./:/usr/src/app
    tty: true